name: Rollout

on:
  workflow_dispatch:

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GA_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GA_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploying services with an env file
        uses: brunocascio/ecs-deploy@v2.2.0
        with:
          args: deploy production-graphacademy-cluster production-graphacademy-service
